---
- hosts: '21'
  user: root
  tasks:
    - name: 陈述式资源管理
      shell: ls

    - name: 查看名称空间
      shell: kubectl get namespace

    - name: 查看集群资源并指定名称空间为default，当名称空间为default的时候，可以不加-n default
      shell: kubectl get all -n default

    - name: 创建名称空间
      shell: kubectl create ns app

    - name: 再次查看名称空间
      shell: kubeclt get ns

    - name: 删除名称空间
      shell: kubectl delete ns app

    - name: 创建Pod控制器
      shell: kubectl create deployment nginx-dp --image=docker.io/library/nginx:1.7.9 -n kube-public

    - name: 使用kubectl describe Pod查看Pod控制器描述信息
      shell: kubectl describe deploy nginx-dp -n kube-public