---
- hosts: '200'
  gather_facts: no
  user: root
  tasks:
    - name: 安装heapster
      shell: mkdir -p /data/k8s-yaml/dashboard/heapster

    - name: 创建heapster资源配置清单
      copy:
        src: ../packages/data/k8s-yaml/dashboard/heapster/{{ item }}
        dest: /data/k8s-yaml/dashboard/heapster/{{ item }}
        mode: 0644
      with_items:
        - rbac.yaml
        - dp.yaml
        - svc.yaml

- hosts: '21'
  gather_facts: no
  user: root
  tasks:
    - name: 拉取heapster镜像
      shell: docker pull quay.io/bitnami/heapster:1.5.4

    - name: 使用kubectl apply -f创建heapster资源
      shell: kubectl apply -f http://k8s-yaml.od.com/dashboard/heapster/{{ item }}
      with_items:
        - rbac.yaml
        - dp.yaml
        - svc.yaml