apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      app: nginx-ds
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: my-nginx
        image: docker.io/library/nginx:1.7.9
#        image: harbor.od.com/nginx:latest
        ports:
        - containerPort: 80
