---
- name: 创建src源码包存放目录
  shell: mkdir -p /opt/src

- name: 添加nginx用户
  shell: useradd -s /sbin/nologin -M nginx
  ignore_errors: yes

- name: 下载nginx源码包
  shell:
    cmd: wget http://nginx.org/download/nginx-1.20.1.tar.gz
    chdir: /opt/src

- name: 解压nginx源码包
  shell: tar xf /opt/src/nginx-1.20.1.tar.gz -C /opt

- name: 下载gcc等编译安装工具包
  shell: yum install -y install gcc pcre pcre-devel zlib zlib-devel openssl openssl-devel

- name: 配置nginx编译使用的模块
  shell:
    cmd: ./configure --sbin-path=/usr/local/sbin --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --user=nginx --group=nginx --with-http_gzip_static_module --with-http_stub_status_module --with-http_ssl_module --with-stream=dynamic
    chdir: /opt/nginx-1.20.1

- name: 编译安装nginx
  shell:
    cmd: make && make install
    chdir: /opt/nginx-1.20.1

- name: 制作nginx软链接
  shell: ln -s /usr/local/sbin/nginx /usr/bin/nginx
  ignore_errors: yes

- name: 将nginx添加到系统自启动服务中
  template:
    src: nginx.service.j2
    dest: /usr/lib/systemd/system/nginx.service
    mode: 0644

- name: 编辑nginx配置文件，非注释的第一行，增加了加载ngx_stream_module.so模块
  # nginx.conf 非注释的第一行，需要加载load_module /usr/local/nginx/modules/ngx_stream_module.so;
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: 使用nginx -t命令检查参数
  shell: nginx -t

- name: 设置开机自启动
  shell: systemctl enable nginx && systemctl start nginx
