---
- hosts: '11'
  user: root
  tasks:
    - name: install bind, 用来自建DNS
      shell: yum install bind -y

    - name: copy packages/etc/named.conf
      copy:
        src: packages/etc/named.conf
        dest: /etc/named.conf
        mode: 0644

    - name: copy packages/etc/named.rfc1912.zones
      copy:
        src: packages/etc/named.rfc1912.zones
        dest: /etc/named/named.rfc1912.zones
        mode: 0644

    - name: copy /var/named/host.com.zone file
      copy:
        src: ./packages/var/named/host.com.zone
        dest: /var/named/host.com.zone
        mode: 0644

    - name: copy /var/named/od.com.zone file
      copy:
        src: ./packages/var/named/od.com.zone
        dest: /var/named/od.com.zone
        mode: 0644

    - name: 启动named服务并设置为开机自启动 想要查看输出内容，在命令后加上 -vv 参数
      shell: systemctl start named && systemctl enable named

    - name: check dig record
      shell: dig -t A hdss7-21.host.com @10.4.7.11 +short

    - name: check named server 想要查看输出内容，在命令后加上 -vv 参数
      shell: named-checkconf

- hosts: nodes
  user: root
  tasks:
    - name: 修改DNS为7.11
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        regexp: '^DNS1='
        line: 'DNS1=10.4.7.11'

    - name: 重启网卡
      shell: systemctl restart network

##   不能加空格
##   - name: echo zone content to named.zone file
##      blockinfile:
##        dest=/etc/named.rfc1912.zones
##        backup=yes
##        content="
##        zone "host.com" IN {\n
##                type  master;\n
##                file  "host.com.zone";\n
##                allow-update { 10.4.7.11; };\n
##        };\n
##
##        zone "od.com" IN {\n
##                type  master;\n
##                file  "od.com.zone";\n
##                allow-update { 10.4.7.11; };\n
##        };\n
##        "

- hosts: docker
  user: root
  tasks:
##      可能会因为网络原因下载安装失败，不推荐使用
##    - name: 删除本地源
##      shell: rm -rf /etc/yum.repos.d/local.repo

    - name: 安装docker源，推荐使用下面的安装方式
      shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

    - name: 安装docker
      shell: yum install docker-ce -y

    - name: 创建docker相关目录
      shell: mkdir -p /etc/docker /data/docker

    - name: 编辑/etc/docker/daemon.json文件，低版本的docker各种起不来。。。。。。。。
      copy:
        src: ./packages/etc/docker/daemon.json
        dest: /etc/docker/daemon.json
        mode: 0644

- hosts: '21'
  user: root
  tasks:
    - name: 修改'21'主机daemon.json中的bip信息
      lineinfile:
        dest: /etc/docker/daemon.json
        regexp: '^(.*)"bip'
        line: '  "bip": "172.7.21.1/24",'

- hosts: '22'
  user: root
  tasks:
    - name: 修改'22'主机daemon.json中的bip信息
      lineinfile:
        dest: /etc/docker/daemon.json
        regexp: '^(.*)"bip'
        line: '  "bip": "172.7.22.1/24",'

- hosts: '200'
  user: root
  tasks:
    - name: 修改'200'主机daemon.json中的bip信息
      lineinfile:
        dest: /etc/docker/daemon.json
        regexp: '^(.*)"bip'
        line: '  "bip": "172.7.200.1/24",'

- hosts: docker
  user: root
  tasks:
    - name: 启动docker并设置开机自启
      shell: systemctl start docker && systemctl enable docker
