---
##   不能加空格
##   - name: echo zone content to named.zone file
##      blockinfile:
##        dest=/etc/named.rfc1912.zones.j2
##        backup=yes
##        content="
##        zone "host.com" IN {\n
##                type  master;\n
##                file  "host.com.zone";\n
##                allow-update { 10.4.7.11; };\n
##        };\n
##
##        zone "od.com" IN {\n
##                type  master;\n
##                file  "od.com.zone";\n
##                allow-update { 10.4.7.11; };\n
##        };\n
##        "

- name: install bind, 用来自建DNS
  shell: yum -y install bind

- name: 上传named conf等文件到/etc目录下
  template:
    src: '{{ item }}.j2'
    dest: /etc/{{ item }}
    mode: 0644
  with_items:
    - named.rfc1912.zones
    - named.conf

- name: 上传zone文件到/vars/named/
  template:
    src: '{{ item }}.j2'
    dest: /var/named/{{ item }}
    mode: 0644
  with_items:
    - od.com.zone
    - host.com.zone

- name: check named server
  shell: named-checkconf

- name: 启动named服务并设置为开机自启动
  shell: systemctl start named && systemctl enable named

- name: check dig record
  shell: dig -t A hdss7-21.host.com @10.4.7.11 +short
  register: std_out

- name: 查看已有的postrouting规则输出结果
  debug: msg={{ std_out.stdout_lines }}
