---
- name: copy rsa.pub
  authorized_key: user=root key="{{ lookup('file', '{{ root_path }}/.ssh/id_rsa.pub') }}"
  tags:
    - sshkey
  ignore_errors: yes

##    - name: fetch copy # 将其它机器公钥拷贝到本机
##      fetch: src=/root/.ssh/id_rsa.pub dest=/Users/liuhuan/Documents/Ansible/K8S/ssh
##
##    - name: append file authorized_keys.log # 公钥拼接成一个文件
##      shell: find /Users/liuhuan/Documents/Ansible/K8S/ssh/* -type f -exec sh -c 'cat {}>>/Users/liuhuan/Documents/Ansible/K8S/ssh/authorized_keys.log' \;
##      run_once: true
##
##    - name: copy hosts # 将处理好的公钥分发给各个机器上
##      copy: src=./ssh/authorized_keys.log dest=/root/.ssh/authorized_keys mode=0600

- name: disable selinux
  template:
    src: config.j2
    dest: /etc/selinux/config
    mode: 0644

- name: stop firewalld
  shell: systemctl stop firewalld && systemctl disable firewalld

- name: 设置时区为上海
  shell: timedatectl set-timezone Asia/Shanghai

- name: install epal
  shell: curl -o /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo

- name: 下载ntpdate
  shell: yum -y install ntpdate

- name: 时间同步
  shell: ntpdate -u cn.ntp.org.cn

- name: install tools
  shell: yum install sshpass wget net-tools telnet tree nmap sysstat lrzsz dos2unix bind-utils -y

## 主机和业务需要分开，但是主机上又跑了业务
## 因此需要设置主机域和业务域，能够将其关联起来
## 后期维护时，如果业务变更（从跑mysql服务变成跑redis服务，没有任何影响）
- name: set host name
  hostname:
    name: "hdss7-{{ ansible_default_ipv4.address.split('.')[-1] }}.host.com"

- name: 修改DNS为7.11
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DNS1='
    line: 'DNS1=10.4.7.11'

- name: 重启机器
  shell: reboot
